[package]
name = "swap_app"
version = "0.1.0"
edition = "202."

[dependencies]
gtk = { version = "0.16.0", features = ["v3_22"] }
reqwest = "0.11.6"
tokio = { version = "1", features = ["full"] }
serde_json = "1.0.64"
